export const SAVE_ACCOUNTS = "SAVE_ACCOUNTS";
export const SAVE_BALANCE = "SAVE_BALANCE";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SHOW_CHANGE_NW_MODAL = "SHOW_CHANGE_NW_MODAL";
export const SAVE_ALL_POOLS_DATA = "SAVE_ALL_POOLS_DATA";
export const SAVE_SINGLE_POOL_DATA = "SAVE_SINGLE_POOL_DATA";
export const SAVE_CURRENT_POOL_ID = "SAVE_CURRENT_POOL_ID";
